language: node_js
node_js:
  - '12'
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: UsUOU6COje2gng7eewvxQnneXr+sMa0gWcXLz1Z1MCdc5nqCMdhip5CGEvpWLN7mmTlKbZz5IAgLE+vCjAqcUbZ7Y5Vt6LCHWELy6XgdyV1p0REC23lURPLTYlmTD4IDk6Il875jahbg91BRxDZe49XeRaZM9IaVagzxSRHrPNGc1tSYPuQ7+WK1GmV0x12VW99KjmqFNbUVlkqGb8AAtMcRY/ZQ/Xf5qUqnDejruSkLIJP9tuTleudI9LM7r9nF3Y0R7MQIijNFMitTkvlLNCoOzOwvn8TiKV+H2omPUFPnBguRkwlqP5dVcF2lbc6lzbVaqAmP/tkmbP68lNjNPkWWOGtMstUEfgylzoOW/SgOiAuxKLcEsTVgBvqNXSuTlc8MzgxAfDDXxq0cv7R/25AsX0KOWN/nJIagil9PxS+fCu6HXi4OGs8xnMN3HxOXHiP2D93JFleQhwLsiGEABM9hhCXX6uTkPFjvy8fWKhOkf9RT9xfNs5iyPvlTxzrNIOjeEgb/Fvhw9TSceqVvBX/lpwhdQQ3ukXEbk1aRNBdtvjeR3xTIGoo1iKbdTzE6R7ediglzivl139ejYMF4Z26qjCZSFJIKvlJkVojiif8/bmSTCGL70JUWuvJeqM84tYy17XNEVA5nbcOz+CFMAR1rt78BtDPgEt/JsrYUSJ8=
  app: banking-nest-unmsm-heroku
notifications:
  email:
    on_failure: change
    on_success: change
